### ISSUE TITLE
libGL error: failed to load driver: radeonsi

### ISSUE THREAD

**Issue by jpotier** [nixinator/nixpkgs-gourse#1]
```
 % nix-shell
hello
gource  -s .05  -a 1 --highlight-users --filename-time 2 --hide filenames --camera-mode overview  --file-filter default.nix  --user-image-dir avatar/ --16000x16000 --max-user-speed 130
libGL error: MESA-LOADER: failed to open radeonsi (search paths /run/opengl-driver/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /run/opengl-driver/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /run/opengl-driver/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  112
  Current serial number in output stream:  111
ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i temporary.ppm -vcodec libx264 -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 -preset slow finalVideo.mp4
```

Oh sadness :'(

What's the problem here? I do have amdgpu up and running, and mesa-demos work fine.

**Comment by nixinator** [comment]
yeah, i've only tested on nvida drivers. It's seems the gourse is either compiled to only support nvida GPU's and associated drivers and middle ware.

It maybe possible to recompile gourse to work with other graphics cards, or it maybe gourse just can't use certain video drivers... or the way that nix/OS presents them to the OS.

the errors look very similar to

 https://github.com/NixOS/nixpkgs/issues/75868
https://github.com/NixOS/nixpkgs/issues/101186

**Comment by jpotier** [comment]
> I was still using an old build of Firefox and Blender built with gcc8, but they're not compatible with the AMD drivers built with gcc9. Upgrading Firefox and Blender fixes the problem for me.

I might have an instance of the same thing, I haven't rebooted in eons, but I continued updating, maybe my `amdgpu` is built with gcc8. I'd need to reboot to test.

**Comment by jpotier** [comment]
> I might have an instance of the same thing, I haven't rebooted in eons, but I continued updating, maybe my `amdgpu` is built with gcc8. I'd need to reboot to test.

Unfortunately, that's not it. Same problem after reboot.

**Comment by nixinator** [comment]
Thanks for trying it out, there's a ton of these problems on the nixpkgs tracker right now. The must be some significant breakage in the AMD drivers. Lets hope someone figures it out soon. Can you open an issue on the nixpkgs tracker for gourse if you have time... and upload some diagnostics and logs.... it's not only blender that's having this problem :-(.

**Comment by nixinator** [comment]
you might be able to get more joy with using an older version of nixpkgs... Apparently this commit 8b6bb39d39af180332dc9a2a6a83049d1ed53ad7

might be more compatible (before the change to a newer glibc).

just change the hash at the top of the nix-shell, and see if it gives better results until there is a mainline fix.

**Comment by jpotier** [comment]
Testing with the older glibc, seem to fail differently:

```
$ nix-shell
hello
gource  -s .05  -a 1 --highlight-users --filename-time 2 --hide filenames --camera-mode overview  --file-filter default.nix  --user-image-dir avatar/ --16000x16000 --max-user-speed 130
gource: SDL initialization failed - Couldn't find matching GLX visual
Try 'gource --help' for more information.

ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i temporary.ppm -vcodec libx264 -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 -preset slow finalVideo.mp4

**Comment by nixinator** [comment]
This is some breakage between drivers, libc6, SDL, OPENGL and all the other chaff that goes to make up a runnable 3D acceleration stack on linux. At this rate i'm going to have to send you an nvida card ;-) . (if it's not your laptop :-) ).

As i can't recreate it here, could you (again if you have time). I'd don't think it's going to be fixed soon, as similar errors have been happening for a few months now in other packages... It would be nice to get to the bottom of it some way... 

There a LOT of moving parts heres, from device drivers, to 3D API's , and then add Xorg.... yikes

Perhaps that's why MESA is called MESA, because it's a MESS? ;-).

maybe a complete stack trace, glxinfo, and other nix-info etc to get a full diag of the problem.

I think GFX stuff like this doesn't get tested on hydra well, because the build machines don't have GFX cards in them, and running automated tests on GUI programme might be tough.

The idea would be to supply hydra machines with every GFX cards ever made, and do integration tests on that... so stuff like this get's caught early.

that's no going to happen soon.... but it's certainly food for thought.

**Comment by jpotier** [comment]
Hey, no worries. The fact that nixpkgs-gourse doesn't run on my machine doesn't remove anything of the nice work you put and result you got, cheers! I was just curious to have an idea of the end result.

**Comment by nixinator** [comment]
I will do a render and upload it somewhere, so you can have a look! :-).

**Comment by raboof** [comment]
Unfortunately it seems MESA is pretty picky about the libraries in `/run/opengl-driver/lib/dri` matching up with the libraries the application has been compiled against.

What works for me is to run it on my current nixpkgs instead of on the version specified in the shell.nix, #2 

Very festive, and I even spotted myself! (though that was pure chance, lovely sprawling activity ;) )

**Comment by jpotier** [comment]
> What works for me is to run it on my current nixpkgs instead of on the version specified in the shell.nix

Yep, that makes it work immediately for me too!

**Comment by nixinator** [comment]
the pinned nixpkgs, should only come into effect if you don't have the 'pkgs' set, which nix-shell should inherit from your channel? I've no idea why your pkgs isn't being set? Unless i've done something special and forgot. :-)
